### ISSUE TITLE
Placing raw glazed flower cerama crashes game

### ISSUE THREAD

**Issue by KatrinkaRose** [Farkoth/Ceramos#1]
I have not tested any other patterns but this one reliably hard crashes out the game every time.

Using mod version 0.2.1

Crash log:
https://pastebin.com/LUGCibz1

**Comment by Farkoth** [comment]
Thanks for reporting this issue! I'll fix it soon.

**Comment by Farkoth** [comment]
Thats got fixed! Please, download new version of mod - v0.2.2

**Comment by Farkoth** [comment]
Thats got fixed! Please, download new version of mod - v0.2.2
